"""empty message

Revision ID: 4719cb2d051d
Revises: None
Create Date: 2016-02-03 16:28:27.887440

"""

# revision identifiers, used by Alembic.
revision = '4719cb2d051d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=256), nullable=False),
    sa.Column('first_name', sa.String(length=256), nullable=False),
    sa.Column('last_name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_first_name'), 'client', ['first_name'], unique=False)
    op.create_index(op.f('ix_client_last_name'), 'client', ['last_name'], unique=False)
    op.create_index(op.f('ix_client_telegram_id'), 'client', ['telegram_id'], unique=True)
    op.create_index(op.f('ix_client_username'), 'client', ['username'], unique=True)
    op.create_table('expert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=256), nullable=False),
    sa.Column('first_name', sa.String(length=256), nullable=False),
    sa.Column('last_name', sa.String(length=256), nullable=False),
    sa.Column('youtube_link', sa.String(), nullable=True),
    sa.Column('youtybe_video_id', sa.String(), nullable=True),
    sa.Column('paypal_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expert_first_name'), 'expert', ['first_name'], unique=False)
    op.create_index(op.f('ix_expert_last_name'), 'expert', ['last_name'], unique=False)
    op.create_index(op.f('ix_expert_paypal_id'), 'expert', ['paypal_id'], unique=False)
    op.create_index(op.f('ix_expert_telegram_id'), 'expert', ['telegram_id'], unique=True)
    op.create_index(op.f('ix_expert_username'), 'expert', ['username'], unique=True)
    op.create_index(op.f('ix_expert_youtube_link'), 'expert', ['youtube_link'], unique=False)
    op.create_index(op.f('ix_expert_youtybe_video_id'), 'expert', ['youtybe_video_id'], unique=False)
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('raw_message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_raw_message'), 'message', ['raw_message'], unique=False)
    op.create_table('link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('expert_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['expert_id'], ['expert.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_link_url'), 'link', ['url'], unique=False)
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('paypal_id', sa.String(), nullable=True),
    sa.Column('payment_gross', sa.Float(), nullable=True),
    sa.Column('payment_fee', sa.Float(), nullable=True),
    sa.Column('payment_net', sa.Float(), nullable=True),
    sa.Column('payment_status', sa.String(), nullable=True),
    sa.Column('txn_id', sa.String(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_payment_fee'), 'payment', ['payment_fee'], unique=False)
    op.create_index(op.f('ix_payment_payment_gross'), 'payment', ['payment_gross'], unique=False)
    op.create_index(op.f('ix_payment_payment_net'), 'payment', ['payment_net'], unique=False)
    op.create_index(op.f('ix_payment_payment_status'), 'payment', ['payment_status'], unique=False)
    op.create_index(op.f('ix_payment_paypal_id'), 'payment', ['paypal_id'], unique=False)
    op.create_index(op.f('ix_payment_txn_id'), 'payment', ['txn_id'], unique=False)
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('expert_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['expert_id'], ['expert.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_amount'), 'ticket', ['amount'], unique=False)
    op.create_index(op.f('ix_ticket_duration'), 'ticket', ['duration'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_duration'), table_name='ticket')
    op.drop_index(op.f('ix_ticket_amount'), table_name='ticket')
    op.drop_table('ticket')
    op.drop_index(op.f('ix_payment_txn_id'), table_name='payment')
    op.drop_index(op.f('ix_payment_paypal_id'), table_name='payment')
    op.drop_index(op.f('ix_payment_payment_status'), table_name='payment')
    op.drop_index(op.f('ix_payment_payment_net'), table_name='payment')
    op.drop_index(op.f('ix_payment_payment_gross'), table_name='payment')
    op.drop_index(op.f('ix_payment_payment_fee'), table_name='payment')
    op.drop_table('payment')
    op.drop_index(op.f('ix_link_url'), table_name='link')
    op.drop_table('link')
    op.drop_index(op.f('ix_message_raw_message'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_expert_youtybe_video_id'), table_name='expert')
    op.drop_index(op.f('ix_expert_youtube_link'), table_name='expert')
    op.drop_index(op.f('ix_expert_username'), table_name='expert')
    op.drop_index(op.f('ix_expert_telegram_id'), table_name='expert')
    op.drop_index(op.f('ix_expert_paypal_id'), table_name='expert')
    op.drop_index(op.f('ix_expert_last_name'), table_name='expert')
    op.drop_index(op.f('ix_expert_first_name'), table_name='expert')
    op.drop_table('expert')
    op.drop_index(op.f('ix_client_username'), table_name='client')
    op.drop_index(op.f('ix_client_telegram_id'), table_name='client')
    op.drop_index(op.f('ix_client_last_name'), table_name='client')
    op.drop_index(op.f('ix_client_first_name'), table_name='client')
    op.drop_table('client')
    ### end Alembic commands ###
